- name: Remove deployment by HEAD
  block:

    - name: Set branch name
      set_fact:
        deploy_branch: "{{ lookup('env', 'HEAD') }}"
      failed_when: deploy_branch == ''

    - name: Check if config exists
      become: true
      stat:
        path: "{{ deploy_branch }}_conf.json"
      register: nginx_set
      failed_when: not nginx_set.stat.exists

    - name: Get used port from memo
      shell: |
        jq -r '."{{ deploy_branch }}"' "{{ deploy_branch }}_conf.json"
      register: port_res

    - name: Close port
      become: true
      community.general.ufw:
        rule: deny
        port: "{{ port_res.stdout }}"
        proto: tcp

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-enabled/airdex_{{ deploy_branch }}.conf"
        - "/etc/nginx/sites-available/airdex_{{ deploy_branch }}.conf"
        - "{{ deploy_branch }}_conf.json"
        - "/var/www/flutterapp/{{ deploy_branch }}"
      become: true
      notify: restart nginx
