name: Create Release and Upload Build Artifacts Android

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Shortify commit sha
        run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT
        id: shortify_commit

      - name: Get branch
        run: echo "ref_short=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Setup GH Actions
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get stable flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Измените по необходимости

      # Установка Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo update-alternatives --config java

      # Установим Java 17 для Gradle
      - name: Set Java 17 for Gradle
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64" > ~/.gradle/gradle.properties

      # Подготовка build директории
      - name: Prepare build directory
        run: |
          flutter clean
          rm -rf build/*
          rm -rf web/src/mm2/*
          rm -rf web/src/kdfi/*
          rm -rf web/dist/*

      - name: Fetch packages and generate assets
        run: |
          flutter pub get
          flutter build apk --release || true
          flutter pub get
          echo "Done fetching packages and generating assets"

      - name: Build GRMS Wallet Android
        run: |
          flutter doctor -v
          flutter build apk --release

      - name: Validate build
        run: |
          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "Error: Android build failed. No APK file found."
            exit 1
          fi

      - name: Archive build artifacts
        run: |
          zip -r build-android.zip build/app/outputs/flutter-apk/

      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: build-android.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name:
