# Rule for running static analysis and code formatting checks on all PRs
name: Validate Code Guidelines
on:
  pull_request:
    branches:
      - '*'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Setup GH Actions
        uses: actions/checkout@v4

      - name: Get stable flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Fetch packages and generate assets
        run: |
          echo "Running \`flutter build\` to generate assets for the deployment build"
          flutter pub get > /dev/null 2>&1
          flutter build web --release > /dev/null 2>&1 || true
          flutter pub get > /dev/null 2>&1
          echo "Done fetching packages and generating assets"

      - name: Validate dart code
        run: |
          flutter analyze
          # Currently skipped due to many changes. Will be enabled in the future after doing full sweep of the codebase
          # dart format --set-exit-if-changed .
